name: merge request

on:
    pull_request:
        branches:
            - 'main'

jobs:
    check:
        uses: tinkoff-mobile-tech/workflows/.github/workflows/android_lib.merge_request.yml@v1
        with:
            java_version: '11'
